# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deployment:
          staging:
            branch: master
            heroku:
              appname: calculator-5
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
      - run: npm install
      - run: npm test

        dependencies:
          override:
            - yarn add ava tap-xunit --dev # or you could use npm
        test:
          override:
            - mkdir -p $CIRCLE_TEST_REPORTS/reports
            - ava --tap | tap-xunit > $CIRCLE_TEST_REPORTS/reports/ava.xml

            # testing with the new branch
        